ls:
  # directory extensions
  .dir: kebab-case | regex:__mocks__

  # js extensions
  .js: regex:([.a-z0-9]*)([-.][a-z0-9]+)*

  # ts extensions
  .ts: regex:([.a-z0-9]*)([-.][a-z0-9]+)*

  src/modules/database/migrations:
    .ts: regex:([.a-z0-9]*)([_.][a-z0-9]+)*

# ignored directories and files
ignore:
  - node_modules
  - .git
  - .github
  - .vscode
  - .husky
  - dist
  - .openapi
  - src/@types
