services:

  gateway:
    build:
      context: ../
      dockerfile: Dockerfile
      target: prod
      args:
        - SERVICE_NAME=gateway
    container_name: gateway
    image: gateway
    env_file:
      - ../.env
    environment:
      # This overrides the .env file
      - HOST=0.0.0.0
    # Mount host directory to docker container to support watch mode
    volumes:
      - gateway
    profiles:
      - prod


    
  gateway-dev:
    build:
      context: ../
      dockerfile: Dockerfile
      target: dev
      args:
        - DOCKER_BUILDKIT=1
        - SERVICE_NAME=gateway
    container_name: gateway-dev
    image: gateway-dev
    env_file:
      - ../.env
    environment:
      # This overrides the .env file
      - HOST=0.0.0.0
    # Mount host directory to docker container to support watch mode
    volumes:
      - ../apps/gateway:/usr/src/app/apps/gateway
      - ../libs:/usr/src/app/libs
      # This ensures that the NestJS container manages the node_modules folder
      # rather than synchronizes it with the host machine
      - gateway-node_modules:/usr/src/app/node_modules
    profiles:
      - dev
    command: >
      sh -c "cd /usr/src/app
      && npm run db:migrate:latest
      && npm run start:dev -- gateway"