services:

  todos:
    build:
      context: ../
      dockerfile: Dockerfile
      target: prod
      args:
        - SERVICE_NAME=todos
    container_name: todos
    image: todos
    env_file:
      - ../.env
    environment:
      # This overrides the .env file
      - HOST=0.0.0.0
    # Mount host directory to docker container to support watch mode
    volumes:
      - todos
    profiles:
      - prod
  


  todos-dev:
    build:
      context: ../
      dockerfile: Dockerfile
      target: dev
      args:
        - DOCKER_BUILDKIT=1
        - SERVICE_NAME=todos
    container_name: todos-dev
    image: todos-dev
    env_file:
      - ../.env
    environment:
      # This overrides the .env file
      - HOST=0.0.0.0
    # Mount host directory to docker container to support watch mode
    volumes:
      - ../apps/todos:/usr/src/app/apps/todos
      - ../libs:/usr/src/app/libs
      # This ensures that the NestJS container manages the node_modules folder
      # rather than synchronizes it with the host machine
      - todos-node_modules:/usr/src/todos/node_modules
    profiles:
      - dev
    command: >
      sh -c "cd /usr/src/app
      && npm run db:migrate:latest
      && npm run start:dev -- todos"